"""
Per-indicator warmup factor lookup.

Source of truth: ``warmup_table.yaml`` (generated by
``scripts/verify_l1_warmup_requirements.py``: 3 symbols × 5 timeframes, adopted
value = max across symbols and timeframes).

FF-STAT Task 2.4（SPEC v32–v45；R4、R5）：
- 每條目具封閉之 ``warmup_class``（window_only／recursive／cumulative／pattern）與 ``period_keys``；
- 查不到之指標一律拋 ``WarmupTableError``——不再有 4.5 後備係數；
- CDL pattern 之 K 取表內具名條目 ``CDL_PATTERN``（取代全域 ``pattern_default_warmup_bars``）。
"""

from __future__ import annotations

import hashlib
import math
import threading
from pathlib import Path
from typing import Any, Dict, Mapping, Optional

import yaml

_YAML_PATH = Path(__file__).resolve().parent / "warmup_table.yaml"

# CDL raw pattern 之具名條目（SPEC §C v39）
PATTERN_ENTRY = "CDL_PATTERN"

_cache_lock = threading.Lock()
_cached_entries: Optional[Dict[str, Dict[str, Any]]] = None


class WarmupTableError(KeyError):
    """倍數表查無指標或條目不可用（FF-STAT R5：不得套後備係數）。"""


def _load() -> Dict[str, Dict[str, Any]]:
    """Load the warmup table once and cache the indicator → entry mapping."""
    global _cached_entries
    if _cached_entries is not None:
        return _cached_entries
    with _cache_lock:
        if _cached_entries is not None:
            return _cached_entries
        with open(_YAML_PATH, "r", encoding="utf-8") as f:
            doc = yaml.safe_load(f) or {}
        _cached_entries = {str(name).upper(): dict(entry) for name, entry in (doc.get("indicators") or {}).items()}
        global _cached_market_scopes
        _cached_market_scopes = tuple(str(s) for s in ((doc.get("_meta") or {}).get("market_scopes") or ()))
        return _cached_entries


_cached_market_scopes: tuple = ()


def measured_market_scopes() -> tuple:
    """倍數表量測所涵蓋之市場（adapter 之 ``market``；表 ``_meta.market_scopes``）。"""
    _load()
    return _cached_market_scopes


def assert_market_measured(market: str) -> None:
    """FFSTAT v52（審查 r35 codex P1-04）：倍數表只以其量測市場之真實資料量得；其他市場之資料不得靜默套用
    ⇒ 生成前 fail-closed。"""
    scopes = measured_market_scopes()
    if str(market) not in scopes:
        raise WarmupTableError(
            f"倍數表未量測市場 {market!r}（已量測：{list(scopes)}）；請以該市場之真實資料執行 "
            f"scripts/verify_l1_warmup_requirements.py 量測後登記（FF-STAT：不得把其他市場之 K 套用於此）")


def warmup_table() -> Mapping[str, Mapping[str, Any]]:
    """倍數表全部條目（名稱大寫）；供 ``stable_mask.instance_k`` 查詢。"""
    return _load()


def get_entry(indicator: str) -> Mapping[str, Any]:
    """單一指標之條目；查無即拋 ``WarmupTableError``（訊息含指標名）。"""
    entry = _load().get(str(indicator).upper())
    if entry is None:
        raise WarmupTableError(f"倍數表查無指標 {indicator!r}（FF-STAT R5：不得套後備係數；請以 "
                               f"scripts/verify_l1_warmup_requirements.py 量測後登記）")
    return entry


def get_warmup_factor(indicator: str) -> float:
    """``indicator`` 之每週期係數（採用值）；查無或該條目無係數（累積型、無參數型）即拋錯。"""
    entry = get_entry(indicator)
    factor = entry.get("recommended_factor")
    if factor is None:
        raise WarmupTableError(f"指標 {indicator!r} 之條目無係數（warmup_class={entry.get('warmup_class')}）")
    return float(factor)


def get_warmup_bars(indicator: str, period: int) -> int:
    """Bars of history needed for ``indicator`` at ``period`` to converge.

    無參數條目（period_keys 為空）回表內登記之 ``k``；累積型回 0（無收斂點，SPEC §C「累積型」）。
    """
    entry = get_entry(indicator)
    if entry.get("warmup_class") == "cumulative":
        return 0
    if not entry.get("period_keys"):
        return int(entry["k"])
    if period <= 0:
        return 0
    return int(math.ceil(period * get_warmup_factor(indicator)))


def get_max_warmup_bars(indicator_periods: Mapping[str, int]) -> int:
    """Largest warmup requirement across a set of (indicator, period) pairs."""
    if not indicator_periods:
        return 0
    return max(get_warmup_bars(name, period) for name, period in indicator_periods.items())


def get_pattern_default_bars() -> int:
    """TA-Lib candlestick patterns（CDL_*）之 K＝表內具名條目 ``CDL_PATTERN`` 之 ``k``。"""
    return int(get_entry(PATTERN_ENTRY)["k"])


def table_sha256() -> str:
    """倍數表檔案位元組之 sha256（設定 hash 之成分：表內容改變即改變遮罩，快取須未命中）。"""
    return hashlib.sha256(_YAML_PATH.read_bytes()).hexdigest()


def reload_table() -> None:
    """Force-reload the YAML (useful in tests or after regeneration)."""
    global _cached_entries
    with _cache_lock:
        _cached_entries = None
    _load()


__all__ = [
    "PATTERN_ENTRY",
    "WarmupTableError",
    "warmup_table",
    "get_entry",
    "get_warmup_factor",
    "get_warmup_bars",
    "get_max_warmup_bars",
    "get_pattern_default_bars",
    "reload_table",
]
