"""
Per-indicator warmup factor lookup.

Source of truth: ``warmup_table.yaml`` (generated by
``scripts/verify_l1_warmup_requirements.py`` with multi-symbol consolidation).

Replaces the legacy blanket ``WARMUP_MULTIPLIER = 4.5`` heuristic with
empirically-verified per-indicator factors at 0.5% scale-normalized error.
"""

from __future__ import annotations

import math
import threading
from pathlib import Path
from typing import Dict, Mapping, Optional

import yaml

# Fallback multiplier used when an indicator is not present in the YAML.
# 4.5 is the legacy blanket value — keeps behavior conservative for unknown
# indicators while the table grows.
_FALLBACK_FACTOR: float = 4.5

# Default warmup for TA-Lib candlestick patterns (CDL_*), which only need a
# few bars of pattern context.
_PATTERN_DEFAULT_BARS: int = 5

_YAML_PATH = Path(__file__).resolve().parent / "warmup_table.yaml"

_cache_lock = threading.Lock()
_cached_factors: Optional[Dict[str, float]] = None
_cached_pattern_bars: int = _PATTERN_DEFAULT_BARS
_cached_cumulative: Dict[str, dict] = {}


def _load() -> Dict[str, float]:
    """Load the warmup table once and cache the indicator → factor mapping."""
    global _cached_factors, _cached_pattern_bars, _cached_cumulative
    if _cached_factors is not None:
        return _cached_factors

    with _cache_lock:
        if _cached_factors is not None:
            return _cached_factors

        if not _YAML_PATH.exists():
            _cached_factors = {}
            return _cached_factors

        with open(_YAML_PATH, "r") as f:
            doc = yaml.safe_load(f) or {}

        factors: Dict[str, float] = {}
        for name, entry in (doc.get("indicators") or {}).items():
            factor = entry.get("recommended_factor")
            if factor is None:
                continue
            # Be conservative: floor at 1.0 (a value < 1 would shrink the
            # required history, which is never desirable for warmup).
            factors[name.upper()] = max(1.0, float(factor))

        _cached_factors = factors
        _cached_pattern_bars = int(
            doc.get("pattern_default_warmup_bars", _PATTERN_DEFAULT_BARS)
        )
        _cached_cumulative = dict(doc.get("cumulative_special_cases") or {})
        return _cached_factors


def get_warmup_factor(indicator: str) -> float:
    """Return the per-period warmup factor for ``indicator``.

    Unknown indicators fall back to the legacy blanket factor (4.5×).
    """
    table = _load()
    return table.get(indicator.upper(), _FALLBACK_FACTOR)


def get_warmup_bars(indicator: str, period: int) -> int:
    """Bars of history needed for ``indicator`` at ``period`` to converge."""
    if period <= 0:
        return 0
    return int(math.ceil(period * get_warmup_factor(indicator)))


def get_max_warmup_bars(indicator_periods: Mapping[str, int]) -> int:
    """Largest warmup requirement across a set of (indicator, period) pairs.

    Example:
        >>> get_max_warmup_bars({"EMA": 144, "ADX": 14})
        # max(ceil(144 * 1.44), ceil(14 * 8.0)) = 208
    """
    if not indicator_periods:
        return 0
    return max(
        get_warmup_bars(name, period)
        for name, period in indicator_periods.items()
        if period and period > 0
    )


def get_pattern_default_bars() -> int:
    """Default warmup bars for TA-Lib candlestick patterns (CDL_*)."""
    _load()
    return _cached_pattern_bars


def reload_table() -> None:
    """Force-reload the YAML (useful in tests or after regeneration)."""
    global _cached_factors
    with _cache_lock:
        _cached_factors = None
    _load()


__all__ = [
    "get_warmup_factor",
    "get_warmup_bars",
    "get_max_warmup_bars",
    "get_pattern_default_bars",
    "reload_table",
]
